@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontColor black
skinparam classFontStyle bold
skinparam sequenceMessageAlign Center
hide empty members

skinparam class {
BackgroundColor white
BorderColor blue
ArrowColor blue
}

class User{
()Choose Formula from FormulaList
}

class AECalculator {
 }

class FormulaList {
Basic Math:
+Addition, Subtraction, Multiplication, Division
+Trigonometric, Hyperbolic, Roots, Exponential Functions
Advanced Math:
+Physics, Chemistry, Geometry
Conversions:
+Metric, SI units, Temperature Conversions
}

class MainMenu {
+Choose 1 for Basic Math
+Choose 2 for Advanced Math
+Choose 3 for Conversions
()Present Formula list
()Input values
()Calculate
}

class Output{
()Show computed value
}


AECalculator --> User
User --> MainMenu
MainMenu .right.> FormulaList
MainMenu --> Output
@enduml
