@startuml
left to right direction
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontColor black
skinparam classFontStyle bold
hide empty members

skinparam class {

BackgroundColor White
BorderColor black
ArrowColor black
}

package AECalculator {
    usecase "Use the calculator" as I1
    usecase "Choose necessary formulas to be used" as I2
    usecase "Input necessary values for the variables given" as I3
    usecase "Calculate expression / equation" as I4
    usecase "Display result" as I5
    usecase "Test for possible bugs" as I6
    usecase "Review" as I7
}

package Admin {
    actor JD as A1
    actor Philip as A2
    actor SirRuiz as A3
}


A1 ---> I6
A2 ---> I6
A3 --> I7

:User: ---> I1
:User: ---> I2
:User: ---> I3
:User: ---> I4
:User: ---> I5

note right of I2 : Formulas include Physics, Chemistry, Geometry, Unit conversions, Functions and Matrices
note right of I4 : Calculation is formula based
@enduml